[package]
name = "booster"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[build]
target = "aarch64-linux-android"

[dependencies]

[package.metadata.cargo-ndk]
linker-args = ["-llog"]
