[package]
name = "booster"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[build]
target = "aarch64-linux-android"

[dependencies]
log = "0.4"
android_logger = "0.13"

[package.metadata.cargo-ndk]
linker-args = ["-llog"]
